# Generated by Django 5.0.4 on 2024-05-15 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(blank=True, db_index=True, default='-', max_length=455, null=True)),
                ('status', models.CharField(blank=True, choices=[('TODO', 'TO DO'), ('INPROGRESS', 'In Progress'), ('REVIEW', 'Review'), ('DONE', 'Done')], max_length=25, null=True, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task_Project_Mapping', to='project.project', verbose_name='project mapping')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task_User_Project_Mapping', to='task.task', verbose_name='project mapping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task_User_Mapping', to=settings.AUTH_USER_MODEL, verbose_name='user mapping')),
            ],
        ),
    ]
